safe: false
port: 4000
baseurl: /
url: http://localhose:4000
source: .
plugins: ./_plugins
future: true
markdown:     rdiscount
permalink:    pretty
paginate:     5
title: shaneknows
description: Let's talk code.